//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBLKatamaran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IonSelectiveMeasurement
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> REQ_TIME { get; set; }
        public Nullable<System.DateTime> RESP_TIME { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> HEADING { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> VALIDMEASURES { get; set; }
        public Nullable<float> IS_CH0 { get; set; }
        public Nullable<float> IS_CH1 { get; set; }
        public Nullable<float> IS_CH2 { get; set; }
        public Nullable<float> IS_CH3 { get; set; }
        public Nullable<float> IS_CH4 { get; set; }
        public Nullable<float> IS_CH5 { get; set; }
        public Nullable<float> IS_CH6 { get; set; }
        public Nullable<float> IS_CH7 { get; set; }
        public Nullable<float> mV_CH0 { get; set; }
        public Nullable<float> mV_CH1 { get; set; }
        public Nullable<float> mV_CH2 { get; set; }
        public Nullable<float> mV_CH3 { get; set; }
        public Nullable<float> mV_CH4 { get; set; }
        public Nullable<float> mV_CH5 { get; set; }
        public Nullable<float> mV_CH6 { get; set; }
        public Nullable<float> mV_CH7 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
