//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBLKatamaran.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KatamaranPBLEntities : DbContext
    {
        public KatamaranPBLEntities()
            : base("name=KatamaranPBLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeepModule> DeepModules { get; set; }
        public virtual DbSet<ElmetronMeasurement> ElmetronMeasurements { get; set; }
        public virtual DbSet<IonSelectiveMeasurement> IonSelectiveMeasurements { get; set; }
        public virtual DbSet<ModbusFrame> ModbusFrames { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
    }
}
