//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBLKatamaran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polls
    {
        public int ID { get; set; }
        public string REQUEST { get; set; }
        public Nullable<System.DateTime> REQ_TIME { get; set; }
        public string RESPONSE { get; set; }
        public Nullable<System.DateTime> RESP_TIME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public bool COMPLETED { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> HEADING { get; set; }
        public string DESCRIPTION { get; set; }
        public bool VALIDMEASURES { get; set; }
        public Nullable<short> ENG_LEFT { get; set; }
        public Nullable<short> ENG_RIGHT { get; set; }
        public Nullable<int> ACCU_VOLTAGE { get; set; }
    }
}
