//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBLKatamaran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESET_ID
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> REQ_TIME { get; set; }
        public Nullable<System.DateTime> RESP_TIME { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> HEADING { get; set; }
        public string DESCRIPTION { get; set; }
        public bool VALIDMEASURES { get; set; }
        public Nullable<float> H_set { get; set; }
        public Nullable<float> H_act { get; set; }
        public Nullable<float> Temperature { get; set; }
        public Nullable<int> Encoder1 { get; set; }
        public Nullable<int> Encoder2 { get; set; }
        public Nullable<int> Modulestatus { get; set; }
    }
}
